### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by mdeering24** [quadrupleslap/scrap#30]
Hi,

I have tried to install your crate with the below commands but neither works because of a missing executable 

`cargo install scrap`
`cargo install --git https://github.com/quadrupleslap/scrap.git`

**error: specified package `scrap v0.5.0` has no binaries**

**Comment by mdeering24** [comment]
I am a doughnut. sorry to bother you 😄

**Comment by weihaigang** [comment]
I have the same problem, how did you solve it in the end?
