### ISSUE TITLE
Always get an error

### ISSUE THREAD

**Issue by marirs** [quadrupleslap/scrap#40]
Hi,

I always get error when calling this:` Capturer::new(display)`
 as `other os error`

It is running as administrator. What am I missing? Is there any specific requirement during compiling? or am I missing something else?

Windows 10 Pro is where I'm trying with Rust 1.52

**Comment by jamespohalloran** [comment]
Hey @marirs , I'm running into this as well. The error specifically being:

> panicked at 'Couldn't begin capture.: Kind(Other)',

I'm using the code from the [screenshot example](https://github.com/quadrupleslap/scrap/blob/master/examples/screenshot.rs)

I see you've closed this issue, did you find a solution?

EDIT: I should note this is on MacOSX

**Comment by pjvds** [comment]
@quadrupleslap Any reason this is closed? I've the same issue as reported by @jamespohalloran and @marirs. Any one of you found the root cause of this?
